import dashboardMock from '../mocks/dashboard.json';
import reportsMock from '../mocks/reports.json';

// ─────────────────────────────────────────────
// Dashboard API
// ─────────────────────────────────────────────

/**
 * Fetch dashboard KPIs and chart data.
 * Optionally accepts filter params (vehicleType, vehicleStatus, region).
 * Backend owns all aggregation — frontend just passes params.
 */
export async function getDashboard(filters = {}) {
  console.log('[API] getDashboard', filters);
  return new Promise((resolve) => {
    setTimeout(() => {
      // Simulate filter-aware response (backend would filter server-side)
      resolve({ ...dashboardMock });
    }, 200);
  });
}

export const getDashboardStats = getDashboard;
export const fetchDashboardStats = getDashboard;

// ─────────────────────────────────────────────
// Reports API
// ─────────────────────────────────────────────

/**
 * Fetch full report data including vehicle rows, highlights and chart data.
 * Accepts filters: { vehicle, dateFrom, dateTo, vehicleType, status }
 */
export async function getReportData(filters = {}) {
  console.log('[API] getReportData', filters);
  return new Promise((resolve) => {
    setTimeout(() => {
      // Simulate filter (backend would filter server-side)
      let rows = [...reportsMock.vehicleReports];

      if (filters.vehicle) {
        rows = rows.filter(r =>
          r.registrationNumber.toLowerCase().includes(filters.vehicle.toLowerCase()) ||
          r.vehicle.toLowerCase().includes(filters.vehicle.toLowerCase())
        );
      }

      resolve({
        ...reportsMock,
        vehicleReports: rows,
      });
    }, 200);
  });
}

/** Download the canonical CSV generated by the authenticated backend endpoint. */
export async function exportReportCSV() {
  const token = localStorage.getItem('kurachel_auth_token');
  if (!token) {
    throw new Error('Sign in with a backend account before exporting a report.');
  }

  const response = await fetch('/api/reports/export', {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!response.ok) {
    throw new Error('Unable to export the report.');
  }

  const blob = await response.blob();
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', 'kurachel-operational-report.csv');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
